apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mysql-operator

resources:
  - upstream

images:
  - name: quay.io/presslabs/mysql-operator-orchestrator
    newName: quay.io/presslabs/mysql-operator-orchestrator
    newTag: 0.4.0
