apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds
- cluster-role-binding.yaml
- cluster-role.yaml
- config-map.yaml
- namespace.yaml
- secret.yaml
- service.yaml
- service-account.yaml
- statefulset.yaml
