apiVersion: v1
kind: Secret
metadata:
  name: mysql-operator-orc
  namespace: mysql-operator
  labels:
    app: mysql-operator
    release: mysql-operator
data:
  TOPOLOGY_USER: "b3JjaGVzdHJhdG9y"
  TOPOLOGY_PASSWORD: "YW1QZHlGN1VmRA=="